/* Full-handshake latency (Stage 6's "handshake completion time, p50/p99"):
 * runs the real client and server state machines against each other over
 * real loopback UDP sockets, repeatedly, and reports wall-clock time from
 * "client starts building ClientHello" to "client has verified the
 * server's Finished and sent its own" -- the complete cost of establishing
 * a connection, not just one primitive in isolation. Same two-threads-
 * over-real-sockets shape as tests/test_interop.c. */
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "nanodtls/client.h"
#include "nanodtls/server.h"
#include "nanodtls/udp.h"

#include "p256_sign_demo.h"

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#else
#include <pthread.h>
#endif

/* Real root/leaf DER bytes + leaf private key -- the same fixture
 * tests/test_interop.c uses (generated by scratchpad/gen_x509_kat.py from a
 * real OpenSSL-issued chain), reused rather than duplicated. */
#include "x509_test_certs.h"

#define ND_BENCH_PORT 42500
#define ITERATIONS 100

static nd_status demo_sign(void *ctx, const uint8_t hash[32], uint8_t out_r[32], uint8_t out_s[32]) {
    (void)ctx;
    return nd_demo_p256_ecdsa_sign(LEAF_KEY_D, hash, out_r, out_s);
}

typedef struct server_run {
    nd_status status;
} server_run;

static void run_server_once(server_run *result) {
    nd_udp_socket sock;
    if (nd_udp_server_bind(&sock, ND_BENCH_PORT) != ND_OK) {
        result->status = ND_ERR_BAD_ARG;
        return;
    }
    nd_server_config config;
    config.cert_der[0] = LEAF_CERT_DER;
    config.cert_der_len[0] = LEAF_CERT_DER_LEN;
    config.cert_count = 1;
    config.sign_fn = demo_sign;
    config.sign_ctx = NULL;

    nd_server_result server_result;
    result->status = nd_server_handshake(&sock, &config, 5000, &server_result);
    nd_udp_close(&sock);
}

#if defined(_WIN32)
static DWORD WINAPI server_thread_main(LPVOID arg) {
    run_server_once((server_run *)arg);
    return 0;
}
#else
static void *server_thread_main(void *arg) {
    run_server_once((server_run *)arg);
    return NULL;
}
#endif

static double now_ns(void) {
    struct timespec ts;
    timespec_get(&ts, TIME_UTC);
    return (double)ts.tv_sec * 1e9 + (double)ts.tv_nsec;
}

static int cmp_double(const void *a, const void *b) {
    double da = *(const double *)a, db = *(const double *)b;
    return (da > db) - (da < db);
}

int main(void) {
    if (nd_udp_global_init() != ND_OK) {
        fprintf(stderr, "bench_handshake: nd_udp_global_init failed\n");
        return 1;
    }

    nd_x509_cert trust_anchor;
    if (nd_x509_parse(ROOT_CERT_DER, ROOT_CERT_DER_LEN, &trust_anchor) != ND_OK) {
        fprintf(stderr, "bench_handshake: trust anchor parse failed\n");
        return 1;
    }

    double samples[ITERATIONS];
    int failures = 0;
    int successes = 0;

    for (int i = 0; i < ITERATIONS; ++i) {
        server_run sresult;
        sresult.status = ND_ERR_BAD_ARG;

#if defined(_WIN32)
        HANDLE thread = CreateThread(NULL, 0, server_thread_main, &sresult, 0, NULL);
#else
        pthread_t thread;
        pthread_create(&thread, NULL, server_thread_main, &sresult);
#endif
        /* Give the freshly-created server thread time to actually reach
         * nd_udp_server_bind() before the client's first send -- 20ms
         * turned out to be too tight under this sandbox's thread-scheduling
         * latency (observed: the client's first few ClientHello attempts
         * consistently raced ahead of the bind, forcing
         * nd_client_handshake's retry loop to burn through several
         * timeouts every iteration -- a benchmark-harness timing issue, not
         * a UDP transport or protocol bug: see
         * scratchpad/test_recv_timing.c, which confirmed nd_udp_recv
         * returns in under a millisecond once data is genuinely queued). */
#if defined(_WIN32)
        Sleep(150);
#else
        struct timespec ts = {0, 150000000L};
        nanosleep(&ts, NULL);
#endif

        nd_udp_socket client_sock;
        if (nd_udp_client_connect(&client_sock, "127.0.0.1", ND_BENCH_PORT) != ND_OK) {
            failures++;
            continue;
        }

        double t0 = now_ns();
        nd_client_result client_result;
        nd_status cst = nd_client_handshake(&client_sock, &trust_anchor, 20270101000000ULL, 500, &client_result);
        double t1 = now_ns();

        nd_udp_close(&client_sock);
#if defined(_WIN32)
        WaitForSingleObject(thread, INFINITE);
        CloseHandle(thread);
#else
        pthread_join(thread, NULL);
#endif

        if (cst != ND_OK || sresult.status != ND_OK) {
            failures++;
            continue;
        }
        samples[successes++] = t1 - t0;
    }

    int n = successes;
    if (n <= 0) {
        fprintf(stderr, "bench_handshake: no successful handshakes (%d failures)\n", failures);
        nd_udp_global_cleanup();
        return 1;
    }

    qsort(samples, (size_t)n, sizeof(double), cmp_double);
    double p50 = samples[n / 2] / 1e6;
    double p99 = samples[(n * 99) / 100 < n ? (n * 99) / 100 : n - 1] / 1e6;
    double min = samples[0] / 1e6;
    double max = samples[n - 1] / 1e6;

    printf("Full DTLS 1.3 handshake latency over real loopback UDP (%d runs, %d failed):\n", n, failures);
    printf("  min=%.2fms  p50=%.2fms  p99=%.2fms  max=%.2fms\n", min, p50, p99, max);
    printf("(includes real X25519, real ECDSA-P256 sign+verify, real X.509 chain verify,\n"
           " real AEAD-protected records, and real socket round-trips -- not a single\n"
           " isolated primitive)\n");

    nd_udp_global_cleanup();
    return 0;
}
