/* Real DTLS 1.3 server, over real UDP sockets, driving nd_server_handshake
 * end to end -- this repo's strongest available interop evidence given
 * OpenSSL 3.5.7 (the version available where this was built) doesn't yet
 * support DTLS 1.3 as a negotiable protocol (checked directly: `openssl
 * s_server -help`/`s_client -help` expose -tls1_3 but only
 * -dtls/-dtls1/-dtls1_2 for DTLS -- no -dtls1_3). See PLAN.md/README
 * "Honest scope" for what that does and doesn't prove.
 *
 * Loads a real P-256 leaf certificate + private key (examples/certs/,
 * generated by and cross-verified with OpenSSL -- see
 * scratchpad/gen_x509_kat.py) and signs CertificateVerify with
 * tools/p256_sign_demo.h's demo-grade (non-constant-time) signer -- see
 * that header for exactly why this is demo-only, never something
 * nanodtls the library does itself. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "nanodtls/server.h"
#include "nanodtls/udp.h"
#include "p256_sign_demo.h"

static uint8_t *read_whole_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len < 0) {
        fclose(f);
        return NULL;
    }
    uint8_t *buf = (uint8_t *)malloc((size_t)len);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)len, f);
    fclose(f);
    if (got != (size_t)len) {
        free(buf);
        return NULL;
    }
    *out_len = (size_t)len;
    return buf;
}

static nd_status demo_sign(void *ctx, const uint8_t hash[32], uint8_t out_r[32], uint8_t out_s[32]) {
    const uint8_t *privkey_d = (const uint8_t *)ctx;
    return nd_demo_p256_ecdsa_sign(privkey_d, hash, out_r, out_s);
}

int main(int argc, char **argv) {
    const char *cert_dir = (argc > 1) ? argv[1] : "examples/certs";
    uint16_t port = (argc > 2) ? (uint16_t)atoi(argv[2]) : 4443;

    char leaf_path[512], key_path[512];
    snprintf(leaf_path, sizeof(leaf_path), "%s/leaf_cert.der", cert_dir);
    snprintf(key_path, sizeof(key_path), "%s/leaf_key_d.bin", cert_dir);

    size_t leaf_len, key_len;
    uint8_t *leaf_der = read_whole_file(leaf_path, &leaf_len);
    uint8_t *privkey_d = read_whole_file(key_path, &key_len);
    if (!leaf_der || !privkey_d || key_len != 32) {
        fprintf(stderr, "server: failed to load cert/key material from %s\n", cert_dir);
        return 1;
    }

    if (nd_udp_global_init() != ND_OK) {
        fprintf(stderr, "server: nd_udp_global_init failed\n");
        return 1;
    }

    nd_udp_socket sock;
    if (nd_udp_server_bind(&sock, port) != ND_OK) {
        fprintf(stderr, "server: bind to port %u failed\n", (unsigned)port);
        return 1;
    }
    fprintf(stderr, "server: listening on 127.0.0.1:%u\n", (unsigned)port);

    nd_server_config config;
    memset(&config, 0, sizeof(config));
    config.cert_der[0] = leaf_der;
    config.cert_der_len[0] = leaf_len;
    config.cert_count = 1;
    config.sign_fn = demo_sign;
    config.sign_ctx = privkey_d;

    nd_server_result result;
    nd_status st = nd_server_handshake(&sock, &config, /*recv_timeout_ms=*/10000, &result);

    nd_udp_close(&sock);
    nd_udp_global_cleanup();
    free(leaf_der);
    free(privkey_d);

    if (st != ND_OK) {
        fprintf(stderr, "server: handshake failed, status=%d\n", (int)st);
        return 1;
    }
    fprintf(stderr, "server: handshake completed successfully\n");
    return 0;
}
